In [1]:
import subprocess,os
import pandas as pd
import requests,json
import numpy as np



pd_JH_data=pd.read_csv('../data/processed/COVID_relational_confirmed.csv',sep=';',parse_dates=[0])
pd_JH_data=pd_JH_data.sort_values('date',ascending=True).reset_index(drop=True).copy()
pd_JH_data.head()

        date    state       country  confirmed
0 2020-01-22  Alberta        Canada        0.0
1 2020-01-22       no  Korea, South        1.0
2 2020-01-22       no        Kosovo        0.0
3 2020-01-22       no        Kuwait        0.0
4 2020-01-22       no    Kyrgyzstan        0.0

In [2]:
test_data=pd_JH_data[((pd_JH_data['country']=='US')|
                     (pd_JH_data['country']=='Germany'))&
                     (pd_JH_data['date']>'2020-03-20')]

In [3]:
test_data

            date state  country  confirmed
15736 2020-03-21    no  Germany    22213.0
15776 2020-03-21    no       US    24508.0
16003 2020-03-22    no  Germany    24873.0
16043 2020-03-22    no       US    33152.0
16267 2020-03-23    no  Germany    29056.0
16307 2020-03-23    no       US    43850.0
16534 2020-03-24    no  Germany    32986.0
16575 2020-03-24    no       US    54112.0
16800 2020-03-25    no  Germany    37323.0
16855 2020-03-25    no       US    66055.0
17066 2020-03-26    no  Germany    43938.0
17106 2020-03-26    no       US    83611.0
17333 2020-03-27    no  Germany    50871.0
17373 2020-03-27    no       US   102101.0
17599 2020-03-28    no  Germany    57695.0
17638 2020-03-28    no       US   122059.0
17864 2020-03-29    no  Germany    62095.0
17919 2020-03-29    no       US   141205.0
18131 2020-03-30    no  Germany    66885.0
18172 2020-03-30    no       US   162707.0
18396 2020-03-31    no  Germany    71808.0
18437 2020-03-31    no       US   188744.0
18661 2020-04-01    no  Germany    77872.0
18717 2020-04-01    no       US   214205.0
18929 2020-04-02    no  Germany    84794.0
18969 2020-04-02    no       US   244610.0
19193 2020-04-03    no  Germany    91159.0
19233 2020-04-03    no       US   276547.0
19460 2020-04-04    no  Germany    96092.0
19515 2020-04-04    no       US   309699.0
...          ...   ...      ...        ...
55903 2020-08-19    no  Germany   229706.0
55943 2020-08-19    no       US  5529824.0
56168 2020-08-20    no  Germany   231292.0
56208 2020-08-20    no       US  5573847.0
56435 2020-08-21    no  Germany   233029.0
56475 2020-08-21    no       US  5622470.0
56701 2020-08-22    no  Germany   233861.0
56741 2020-08-22    no       US  5667070.0
56967 2020-08-23    no  Germany   234494.0
57006 2020-08-23    no       US  5701645.0
57233 2020-08-24    no  Germany   236122.0
57273 2020-08-24    no       US  5739536.0
57499 2020-08-25    no  Germany   237583.0
57539 2020-08-25    no       US  5777710.0
57765 2020-08-26    no  Germany   239010.0
57805 2020-08-26    no       US  5821819.0
58030 2020-08-27    no  Germany   240571.0
58085 2020-08-27    no       US  5867785.0
58297 2020-08-28    no  Germany   242126.0
58337 2020-08-28    no       US  5913941.0
58561 2020-08-29    no  Germany   242835.0
58601 2020-08-29    no       US  5961094.0
58829 2020-08-30    no  Germany   243305.0
58870 2020-08-30    no       US  5996431.0
59093 2020-08-31    no  Germany   244802.0
59133 2020-08-31    no       US  6030587.0
59361 2020-09-01    no  Germany   246015.0
59402 2020-09-01    no       US  6073840.0
59626 2020-09-02    no  Germany   247411.0
59668 2020-09-02    no       US  6113510.0

[332 rows x 4 columns]

In [4]:
test_data.groupby(['country']).agg(np.max)

              date state  confirmed
country
Germany 2020-09-02    no   247411.0
US      2020-09-02    no  6113510.0

In [ ]:
# %load ../src/features/build_features.py
import subprocess,os
import pandas as pd
import requests,json
import numpy as np
from sklearn import linear_model

reg= linear_model.LinearRegression(fit_intercept=True)




def get_doubling_time_via_regression(in_array):
    ''' Use a linear regression to approximate the doubling rate'''
    #print(in_array)    
    
    #y=np.array(in_array)
    #x=np.arange(-1,2).reshape(-1,1)
    
    y=np.array(in_array)
    x=np.arange(len(y)).reshape(-1,1)
    
    assert len(in_array==3)
    reg.fit(x,y)
    intercept=reg.intercept_
    slope=reg.coef_
    
    return intercept/slope

#if __name__== '__main__':
#    test_data=np.array([2,4,6])
#    result=get_doubling_time_via_regression(test_data)
#    print('the test slope is: '+str(result))

In [ ]:
test_data.groupby(['state','country']).agg(np.max)

                    date  confirmed
state country
no    Germany 2020-09-02   247411.0
      US      2020-09-02  6113510.0

In [ ]:
#test_data.groupby(['state','country']).apply(get_doubling_time_via_regression)

In [ ]:
def rolling_reg(df_input,col='confirmed'):
    
    '''input has to be a data frame'''
    '''return is single series (mandatory for group by apply)'''

    days_back=3
    result=df_input[col].rolling(
                window=days_back,
                min_periods=days_back).apply(get_doubling_time_via_regression,raw=False)

    return result

In [ ]:
test_data[['state','country','confirmed']].groupby(['state','country']
                                                  ).apply(rolling_reg,'confirmed')

state  country
no     Germany  15736           NaN
                16003           NaN
                16267      6.417994
                16534      6.142035
                16800      7.012983
                17066      5.954407
                17333      5.501919
                17599      6.390371
                17864      9.136671
                18131     12.541893
                18396     12.781393
                18661     12.140681
                18929     11.037271
                19193     11.735506
                19460     15.052694
                19726     20.372453
                19991     26.427355
                20259     26.511936
                20524     20.792179
                20790     20.495848
                21057     25.565108
                21323     35.198404
                21589     42.982990
                21855     48.423444
                22121     73.043747
                22387     55.424411
                22653     41.468318
                22918     40.525988
                23185     48.898063
                23450     74.684007
                            ...
       US       51953     90.685726
                52219     85.443196
                52484     84.797301
                52751     81.858790
                53017     85.422707
                53282     95.884837
                53549    103.606172
                53814    104.735503
                54081     98.879424
                54346     95.442858
                54613     89.696852
                54879     93.607140
                55144    118.145185
                55411    138.992250
                55677    134.744110
                55943    118.866789
                56208    121.243661
                56475    119.358792
                56741    119.595325
                57006    142.068603
                57273    156.391062
                57539    149.913832
                57805    139.483170
                58085    128.279778
                58337    126.392986
                58601    125.767479
                58870    143.433394
                59133    171.565218
                59402    154.889350
                59668    145.464688
Name: confirmed, Length: 332, dtype: float64

In [ ]:
test_data

            date state  country  confirmed
15736 2020-03-21    no  Germany    22213.0
15776 2020-03-21    no       US    24508.0
16003 2020-03-22    no  Germany    24873.0
16043 2020-03-22    no       US    33152.0
16267 2020-03-23    no  Germany    29056.0
16307 2020-03-23    no       US    43850.0
16534 2020-03-24    no  Germany    32986.0
16575 2020-03-24    no       US    54112.0
16800 2020-03-25    no  Germany    37323.0
16855 2020-03-25    no       US    66055.0
17066 2020-03-26    no  Germany    43938.0
17106 2020-03-26    no       US    83611.0
17333 2020-03-27    no  Germany    50871.0
17373 2020-03-27    no       US   102101.0
17599 2020-03-28    no  Germany    57695.0
17638 2020-03-28    no       US   122059.0
17864 2020-03-29    no  Germany    62095.0
17919 2020-03-29    no       US   141205.0
18131 2020-03-30    no  Germany    66885.0
18172 2020-03-30    no       US   162707.0
18396 2020-03-31    no  Germany    71808.0
18437 2020-03-31    no       US   188744.0
18661 2020-04-01    no  Germany    77872.0
18717 2020-04-01    no       US   214205.0
18929 2020-04-02    no  Germany    84794.0
18969 2020-04-02    no       US   244610.0
19193 2020-04-03    no  Germany    91159.0
19233 2020-04-03    no       US   276547.0
19460 2020-04-04    no  Germany    96092.0
19515 2020-04-04    no       US   309699.0
...          ...   ...      ...        ...
55903 2020-08-19    no  Germany   229706.0
55943 2020-08-19    no       US  5529824.0
56168 2020-08-20    no  Germany   231292.0
56208 2020-08-20    no       US  5573847.0
56435 2020-08-21    no  Germany   233029.0
56475 2020-08-21    no       US  5622470.0
56701 2020-08-22    no  Germany   233861.0
56741 2020-08-22    no       US  5667070.0
56967 2020-08-23    no  Germany   234494.0
57006 2020-08-23    no       US  5701645.0
57233 2020-08-24    no  Germany   236122.0
57273 2020-08-24    no       US  5739536.0
57499 2020-08-25    no  Germany   237583.0
57539 2020-08-25    no       US  5777710.0
57765 2020-08-26    no  Germany   239010.0
57805 2020-08-26    no       US  5821819.0
58030 2020-08-27    no  Germany   240571.0
58085 2020-08-27    no       US  5867785.0
58297 2020-08-28    no  Germany   242126.0
58337 2020-08-28    no       US  5913941.0
58561 2020-08-29    no  Germany   242835.0
58601 2020-08-29    no       US  5961094.0
58829 2020-08-30    no  Germany   243305.0
58870 2020-08-30    no       US  5996431.0
59093 2020-08-31    no  Germany   244802.0
59133 2020-08-31    no       US  6030587.0
59361 2020-09-01    no  Germany   246015.0
59402 2020-09-01    no       US  6073840.0
59626 2020-09-02    no  Germany   247411.0
59668 2020-09-02    no       US  6113510.0

[332 rows x 4 columns]

In [ ]:
pd_DR_result=pd_JH_data[['state','country','confirmed']].groupby(['state','country']).apply(rolling_reg,'confirmed').reset_index()

In [ ]:
pd_DR_result